version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database  
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./src/db.php:/docker-entrypoint-initdb.d/db.php

